In [3]:
import wiggum as wg
import pandas as pd
import numpy as np
from scipy.stats import kendalltau

In [74]:
labeled_df=wg.LabeledDataFrame('../data/genderpaygap')

In [63]:
labeled_df.meta_df['role']='nan'
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var,roles
variable,,,,,,
role,object,categorical,"[splitby, [independent, dependent]]",False,NaN,nan
gender,object,categorical,"[splitby, [independent, dependent]]",False,NaN,nan
Headcount,int64,ordinal,[ignore],True,NaN,nan
MeanHourlyPay,int64,continuous,"[[independent, dependent]]",False,Headcount,nan

In [76]:
roles={'role':['splitby', 'independent'], 'gender':['splitby', 'independent'], 'Headcount':['ignore'], 'MeanHourlyPay':['dependent']}
labeled_df.set_roles(roles)

c:\users\pad39\appdata\local\programs\python\python38\lib\site-packages\wiggum\labeled_dataframe.py:367: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.meta_df['role'][k] = v

In [77]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
role,object,categorical,"[splitby, independent]",False,NaN
gender,object,categorical,"[splitby, independent]",False,NaN
Headcount,int64,ordinal,[ignore],True,NaN
MeanHourlyPay,int64,continuous,[dependent],False,Headcount

In [81]:
binary=wg.Mean_Rank_Trend()
binary.get_trend_vars(labeled_df)

(['MeanHourlyPay'], ['role', 'gender'])

In [83]:
binary.get_trends(labeled_df.df, 'agg_trend')

,independent,dependent,agg_trend,agg_trend_strength,trend_type
0,role,MeanHourlyPay,"[Support, R&D engineering, Sales, Management]",0.8737,rank_trend
1,gender,MeanHourlyPay,"[F, M]",0.6822,rank_trend

In [29]:
labeled_df=wg.LabeledDataFrame(r'../data/multi_decision_admisions')

In [8]:
labeled_df.df

,department,gender,decision,race,decision_noise,decision_gender,decision_race
,,,,,,,
0,3,M,1,W,1,1,1
1,3,M,1,H,0,0,1
2,0,F,0,W,0,0,0
3,1,F,0,H,0,0,1
4,3,M,1,W,1,1,0
...,...,...,...,...,...,...,...
995,2,F,1,W,1,1,1
996,3,M,0,W,0,0,0
997,3,M,0,W,0,0,1
998,0,F,0,W,1,0,0
999,3,M,0,B,0,0,0

In [30]:
roles={'department':['splitby', 'independent'], 'gender':['splitby', 'independent'],
       'decision':['dependent']}
labeled_df.set_roles(roles)

c:\users\pad39\appdata\local\programs\python\python38\lib\site-packages\wiggum\labeled_dataframe.py:367: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.meta_df['role'][k] = v

In [11]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
department,int64,categorical,"[splitby, [independent, dependent]]",False,NaN
gender,object,categorical,"[splitby, [independent, dependent]]",False,NaN
decision,int64,binary,"[[independent, dependent], groundtruth]",False,NaN
race,object,categorical,"[splitby, [independent, dependent]]",False,NaN
decision_noise,int64,binary,"[[independent, dependent], prediction]",False,NaN
decision_gender,int64,binary,"[[independent, dependent], prediction]",False,NaN
decision_race,int64,binary,"[[independent, dependent], prediction]",False,NaN

In [13]:
binary=wg.Mean_Rank_Trend()
binary.get_trend_vars(labeled_df)

(['decision'], ['department', 'gender'])

In [16]:
binary.get_trends(labeled_df.df, 'agg_trend')

  independent dependent     agg_trend  agg_trend_strength  trend_type
0  department  decision  [1, 0, 3, 2]               0.011  rank_trend
1      gender  decision        [F, M]               0.026  rank_trend

In [17]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
department,int64,categorical,"[splitby, independent]",False,NaN
gender,object,categorical,"[splitby, independent]",False,NaN
decision,int64,binary,[dependent],False,NaN
race,object,categorical,"[splitby, [independent, dependent]]",False,NaN
decision_noise,int64,binary,"[[independent, dependent], prediction]",False,NaN
decision_gender,int64,binary,"[[independent, dependent], prediction]",False,NaN
decision_race,int64,binary,"[[independent, dependent], prediction]",False,NaN

In [31]:
roles={'race':['splitby', 'independent'], 'decision_noise':['dependent'], 'decision_gender':['dependent'],
     'decision_race':['dependent']}
labeled_df.set_roles(roles)

In [36]:
binary=wg.Mean_Rank_Trend()
binary.get_trend_vars(labeled_df)

(['decision', 'decision_noise', 'decision_gender', 'decision_race'],
 ['department', 'gender', 'race'])

In [33]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
department,int64,categorical,"[splitby, independent]",False,NaN
gender,object,categorical,"[splitby, independent]",False,NaN
decision,int64,binary,[dependent],False,NaN
race,object,categorical,"[splitby, independent]",False,NaN
decision_noise,int64,binary,[dependent],False,NaN
decision_gender,int64,binary,[dependent],False,NaN
decision_race,int64,binary,[dependent],False,NaN

In [40]:
binary.get_trends(labeled_df.df, 'agg_trend')

   independent        dependent     agg_trend  agg_trend_strength  trend_type
0   department         decision  [1, 0, 3, 2]              0.0110  rank_trend
1       gender         decision        [F, M]              0.0260  rank_trend
2         race         decision     [B, H, W]              0.0220  rank_trend
3   department   decision_noise  [1, 0, 3, 2]              0.0112  rank_trend
4       gender   decision_noise        [F, M]              0.0260  rank_trend
5         race   decision_noise     [B, H, W]              0.0165  rank_trend
6   department  decision_gender  [1, 0, 3, 2]              0.0166  rank_trend
7       gender  decision_gender        [M, F]              0.0899  rank_trend
8         race  decision_gender     [H, W, B]              0.0476  rank_trend
9   department    decision_race  [1, 0, 3, 2]              0.0413  rank_trend
10      gender    decision_race        [F, M]              0.0136  rank_trend
11        race    decision_race     [W, H, B]              0.0020  rank_trend

In [51]:
labeled_df=wg.LabeledDataFrame('../data/RateSPdataDeptRace')

In [52]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
department,int64,categorical,"[splitby, [independent, dependent]]",False,NaN
gender,object,categorical,"[splitby, [independent, dependent]]",False,NaN
decision,int64,binary,"[[independent, dependent]]",False,NaN
race,object,categorical,"[splitby, [independent, dependent]]",False,NaN

In [53]:
roles={'department':['splitby', 'independent'], 'gender':['splitby', 'independent'],
     'decision':['dependent'], 'race':['splitby', 'independent']}
labeled_df.set_roles(roles)

c:\users\pad39\appdata\local\programs\python\python38\lib\site-packages\wiggum\labeled_dataframe.py:367: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.meta_df['role'][k] = v

In [54]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
department,int64,categorical,"[splitby, independent]",False,NaN
gender,object,categorical,"[splitby, independent]",False,NaN
decision,int64,binary,[dependent],False,NaN
race,object,categorical,"[splitby, independent]",False,NaN

In [55]:
binary.get_trend_vars(labeled_df)

(['decision'], ['department', 'gender', 'race'])

In [57]:
binary.get_trends(labeled_df.df, 'agg_trend')

  independent dependent     agg_trend  agg_trend_strength  trend_type
0  department  decision  [1, 0, 3, 2]               0.011  rank_trend
1      gender  decision        [F, M]               0.026  rank_trend
2        race  decision     [B, H, W]               0.022  rank_trend

In [59]:
labeled_df=wg.LabeledDataFrame('../data/ldf_state_hit_rate_min_cols_COCTFLILMDMAMOMTNENCOHRISCTXVTWAWI')

In [60]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
state,object,categorical,"[independent, splitby]",False,NaN
year,int64,ordinal,[independent],False,NaN
driver_gender,object,categorical,"[independent, splitby]",False,NaN
driver_race,object,categorical,"[independent, splitby]",False,NaN
decriminalization,int64,categorical,[splitby],False,NaN
medical,int64,categorical,[splitby],False,NaN
recreational,int64,categorical,[splitby],False,NaN
no_reforms,int64,False,[splitby],False,NaN
search_conducted_false,float64,continuous,[ignore],True,NaN
search_conducted_true,float64,continuous,[ignore],True,NaN
search_conducted_rate,float64,continuous,[dependent],False,num_stops
contraband_found_false,float64,continuous,[ignore],True,NaN
contraband_found_true,float64,continuous,[ignore],True,NaN
contraband_found_rate,float64,continuous,[dependent],False,num_stops
hit_false,float64,continuous,[ignore],True,NaN
hit_true,float64,continuous,[ignore],True,NaN
hit_rate,float64,continuous,[dependent],False,search_conducted_true
num_stops,float64,continuous,[dependent],True,NaN

In [61]:
roles={'decriminalization':['independent', 'splitby'], 'medical':['independent', 'splitby'], 
      'recreational':['independent', 'splitby']}
labeled_df.set_roles(roles)

c:\users\pad39\appdata\local\programs\python\python38\lib\site-packages\wiggum\labeled_dataframe.py:367: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.meta_df['role'][k] = v

In [62]:
binary.get_trend_vars(labeled_df)

(['search_conducted_rate', 'contraband_found_rate', 'hit_rate', 'num_stops'],
 ['state',
  'driver_gender',
  'driver_race',
  'decriminalization',
  'medical',
  'recreational'])

In [63]:
binary.get_trends(labeled_df.df, 'agg_trends')

,independent,dependent,agg_trends,agg_trends_strength,trend_type
0,state,search_conducted_rate,"[CO, NC, VT, WI, MD, MA, CT, TX, SC, WA, RI, I...",0.3881,rank_trend
1,driver_gender,search_conducted_rate,"[F, M]",0.2519,rank_trend
2,driver_race,search_conducted_rate,"[Asian, White, Other, Black, Hispanic]",0.2772,rank_trend
3,decriminalization,search_conducted_rate,"[1, 0]",0.4198,rank_trend
4,medical,search_conducted_rate,"[0, 1]",0.1087,rank_trend
5,recreational,search_conducted_rate,"[1, 0]",0.1752,rank_trend
6,state,contraband_found_rate,"[NC, CO, MD, WA, CT, SC, TX, WI, IL, MA, VT, A...",0.0201,rank_trend
7,driver_gender,contraband_found_rate,"[F, M]",0.1797,rank_trend
8,driver_race,contraband_found_rate,"[Asian, White, Other, Hispanic, Black]",0.0716,rank_trend
9,decriminalization,contraband_found_rate,"[1, 0]",0.2426,rank_trend
10,medical,contraband_found_rate,"[0, 1]",0.0869,rank_trend
11,recreational,contraband_found_rate,"[1, 0]",0.0174,rank_trend
12,state,hit_rate,"[WA, NC, IL, AZ, SC, MD, TX, CT, RI, MA, WI, C...",0.2193,rank_trend
13,driver_gender,hit_rate,"[F, M]",0.0433,rank_trend
14,driver_race,hit_rate,"[Asian, Hispanic, Other, Black, White]",0.0023,rank_trend
15,decriminalization,hit_rate,"[0, 1]",0.2050,rank_trend
16,medical,hit_rate,"[1, 0]",0.0797,rank_trend
17,recreational,hit_rate,"[1, 0]",0.2949,rank_trend
18,state,num_stops,"[RI, VT, WI, CT, MD, MA, AZ, CO, IL, NC, WA, S...",0.3209,rank_trend
19,driver_gender,num_stops,"[F, M]",0.1164,rank_trend
20,driver_race,num_stops,"[Other, Asian, Black, Hispanic, White]",0.4996,rank_trend
21,decriminalization,num_stops,"[0, 1]",0.0511,rank_trend
22,medical,num_stops,"[1, 0]",0.0606,rank_trend
23,recreational,num_stops,"[1, 0]",0.0835,rank_trend

In [66]:
labeled_df=wg.LabeledDataFrame('../data/ricci.csv')

In [68]:
roles={'Position':['splitby', 'independent'], 'Oral':['dependent'], 
      'Written':['dependent'], 'Race':['splitby', 'independent'], 'Combine':['dependent']}
var_types={'Position':'categorical', 'Oral':'continuous', 'Written':'continuous', 'Race':'categorical',
          'Combine':'continuous'}
labeled_df.set_roles(roles)
labeled_df.set_var_types(var_types)

In [69]:
labeled_df.meta_df

            dtype     var_type                    role isCount weighting_var
variable
Position   object  categorical  [splitby, independent]     NaN           NaN
Oral      float64   continuous             [dependent]     NaN           NaN
Written     int64   continuous             [dependent]     NaN           NaN
Race       object  categorical  [splitby, independent]     NaN           NaN
Combine   float64   continuous             [dependent]     NaN           NaN

In [47]:
def categorical_kendalltau(list1,list2):
    
#     if len()
    list_diff = set(list1).difference(set(list2))
    
    all_vals = list1.copy()
    all_vals.extend(list_diff)
    
    numeric_map = {a:i for i,a in enumerate(all_vals)}
    numeric_a = [numeric_map[a] for a in list1]
    numeric_b = [numeric_map[b] for b in list2]
    

    n_a = len(numeric_a)
    n_b = len(numeric_b)
    if n_a < n_b:
        append_nums = list(range(n_a,n_b))
        numeric_a.extend(append_nums)
    if n_a > n_b:
        append_nums = list(range(n_b,n_a))
        numeric_b.extend(append_nums)

    return kendalltau(numeric_a,numeric_b)

In [22]:
labeled_df.meta_df

,dtype,var_type,role,isCount,weighting_var
variable,,,,,
role,object,categorical,"[splitby, [independent, dependent]]",False,NaN
gender,object,categorical,"[splitby, [independent, dependent]]",False,NaN
Headcount,int64,ordinal,[ignore],True,NaN
MeanHourlyPay,int64,continuous,"[[independent, dependent]]",False,Headcount

In [70]:
binary.get_trend_vars(labeled_df)

(['Oral', 'Written', 'Combine'], ['Position', 'Race'])

In [72]:
binary.get_trends(labeled_df.df, 'agg_trends')

,independent,dependent,agg_trends,agg_trends_strength,trend_type
0,Position,Oral,"[Lieutenant, Captain]",0.1403,rank_trend
1,Race,Oral,"[H, B, W]",0.1248,rank_trend
2,Position,Written,"[Lieutenant, Captain]",0.0282,rank_trend
3,Race,Written,"[B, H, W]",0.1522,rank_trend
4,Position,Combine,"[Lieutenant, Captain]",0.1403,rank_trend
5,Race,Combine,"[B, H, W]",0.3581,rank_trend

In [44]:
list_a=list(labeled_df.df['role'])
list_b=list(labeled_df.df['gender'])
list_a

['Management',
 'R&D engineering',
 'Sales',
 'Support',
 'Management',
 'R&D engineering',
 'Sales',
 'Support']

In [51]:
categorical_kendalltau(list_b, list_b)

KendalltauResult(correlation=1.0, pvalue=0.0081509715935027)